// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/macmini/Desktop/workSpace/y/yiping-react-cli/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import UserOutlined from '/Users/macmini/Desktop/workSpace/y/yiping-react-cli/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, UserOutlined };
