// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'E:/workSpace/gitee/yiping-react-cli/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import UserOutlined from 'E:/workSpace/gitee/yiping-react-cli/node_modules/@ant-design/icons/es/icons/UserOutlined';
export default { SmileOutlined, UserOutlined };
