// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { useKeepOutlets } from '@umijs/max';
  
        const Layout = () => {
          const element = useKeepOutlets();
          return <>{element}</>;
        };
  
        export default Layout;
